GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Authorization: bearer X
Content-Type: application/json

{
    "title": "Title",
    "author": "Author",
    "url": "example.com",
    "likes": 69
}
###
DELETE http://localhost:3003/api/blogs/X
Authorization: bearer X
###
POST http://localhost:3003/api/blogs/X/comments
Content-Type: application/json

{
    "comment": "test2"
}